repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args:
            - --profile=black
-   repo: local
    hooks:
    -   id: generate-model-catalog
        name: generate model catalog
        entry: python scripts/generate_model_catalog.py
        language: python
        pass_filenames: false
